[project]
name = "datascience_as_a_service"
requires-python = ">=3.14,<3.15"
version = "0.1.0"
dependencies = [
    "boto3>=1.42.86",
    "boto3-stubs[s3]>=1.42.88",
    "dagster==1.12.22",
    "dagster-mlflow>=0.28.22",
    "dagster-postgres>=0.28.22",
    "deltalake>=1.5.0",
    "duckdb>=1.5.1",
    "fastexcel>=0.19.0",
    "httpx>=0.28.1",
    "mlflow>=3.11.1",
    "numpy>=2.2.6",
    "optuna>=4.8.0",
    "optuna-integration[xgboost]>=4.8.0",
    "pandas>=2.3.3",
    "polars>=1.39.3",
    "prophet>=1.3.0",
    "s3fs>=0.4.2",
    "scikit-learn>=1.8.0",
    "xgboost>=3.2.0",
]

[dependency-groups]
dev = [
    "dagster-webserver",
    "dagster-dg-cli",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
force-include = { "pyproject.toml" = "pyproject.toml" }

[tool.dg]
directory_type = "project"

[tool.dg.project]
root_module = "datascience_as_a_service"
registry_modules = [
    "datascience_as_a_service.components.*",
]


